POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "Vamo que vamo delhe que delhe vaneira!!!",
    "User": {
        "Name": "Cassio Gamarra"
    }
}
###
GET http://localhost:3000/mail-list
### 
POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "emails": ["cassio1515@hotmail.com", "cassiogamarra@outlook.com", "roziana@gmail.com"]
}
