on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.3.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0
      - name: Install Yarn
        run: npm install yarn -g
